name: Integration & Unit test

on:
  pull_request:
    branches:
      - MOODLE_*_STABLE

jobs:
  PHPUnit:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - php: 8.3
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: mysqli
            experimental: false
            dependencies: |
              praxisdigital/local_mxaimanager@MOODLE_50_STABLE
          - php: 8.4
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: mysqli
            experimental: false
            dependencies: |
              praxisdigital/local_mxaimanager@MOODLE_50_STABLE
          - php: 8.3
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: sqlsrv
            experimental: false
            dependencies: |
              praxisdigital/local_mxaimanager@MOODLE_50_STABLE
          - php: 8.4
            os: ubuntu-latest
            moodle: MOODLE_500_STABLE
            dbtype: sqlsrv
            experimental: false
            dependencies: |
              praxisdigital/local_mxaimanager@MOODLE_50_STABLE

    steps:
      - name: Unit testing & integration testing
        uses: praxisdigital/moodle-test-action@master
        with:
          plugin: assignsubmission_pxaiwriter
          plugin-path: mod/assign/submission/pxaiwriter
          os: ${{ matrix.os }}
          php: ${{ matrix.php }}
          dbtype: ${{ matrix.dbtype }}
          moodle: ${{ matrix.moodle }}
          experimental: ${{ matrix.experimental }}
          dependencies: ${{ matrix.dependencies }}
          PRIVATE_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
