name: Integration & Unit test

on:
  pull_request:
    branches:
      - master

env:
  php: 8.0

jobs:
  PHPUnit:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          ## Moodle 4.0+ with PHP 7.4
          - os: ubuntu-20.04
            php: 7.4
            db: mysqli
            moodle: MOODLE_400_STABLE
            plugin_branch: MOODLE_40_STABLE
            experimental: false
          ## Moodle 4.0+ with PHP 8.0
          - os: ubuntu-22.04
            php: 8.0
            db: mysqli
            moodle: MOODLE_400_STABLE
            plugin_branch: MOODLE_40_STABLE
            experimental: false
          ## Moodle 4.1+ with PHP 8.1
          - os: ubuntu-22.04
            php: 8.1
            db: mysqli
            moodle: MOODLE_401_STABLE
            plugin_branch: MOODLE_40_STABLE
            experimental: false
          ## Moodle dev with PHP 8.2
          - os: ubuntu-22.04
            php: 8.2
            db: mysqli
            moodle: master
            plugin_branch: MOODLE_40_STABLE
            experimental: true
    steps:
      - name: Setting up DB mysql
        if: ${{ matrix.db == 'mysqli' }}
        uses: johanmeiring/mysql-action@tmpfs-patch
        with:
          collation server: utf8mb4_danish_ci
          mysql version: 8
          mysql database: test
          mysql user: test
          mysql password: test
          use tmpfs: true

      - name: Setting up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          ini-values: 'max_input_vars=5000'

      - name: Checking out code from moodle/moodle
        uses: actions/checkout@v3
        with:
          repository: moodle/moodle
          ref: ${{ matrix.moodle }}

      - name: Check out code from ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/mod/assign/submission/pxaiwriter
          ref: ${{ github.ref }}

      - name: Setting up PHPUnit
        env:
          dbtype: ${{ matrix.db }}
        run: |
          echo "pathtophp=$(which php)" >> $GITHUB_ENV # Inject installed pathtophp to env. The template config needs it.
          cp $GITHUB_WORKSPACE/.github/workflows/config-template.php $GITHUB_WORKSPACE/config.php
          mkdir $GITHUB_WORKSPACE/../moodledata
          sudo locale-gen en_AU.UTF-8
          php $GITHUB_WORKSPACE/admin/tool/phpunit/cli/init.php --no-composer-self-update
      - name: Running PHPUnit tests
        env:
          dbtype: ${{ matrix.db }}
        run: $GITHUB_WORKSPACE/vendor/bin/phpunit -c $GITHUB_WORKSPACE/phpunit.xml --testsuite=assignsubmission_pxaiwriter_testsuite -v --testdox