name: Integration & Unit test

on:
  pull_request:
    branches:
      - MOODLE_*_STABLE

jobs:
  PHPUnit:
    runs-on: ${{ env.OS }}
    continue-on-error: ${{ env.EXPERIMENTAL }}
    env:
      OS: ubuntu-latest
      EXPERIMENTAL: false
      DEPENDENCIES: |
        praxisdigital/local_mxaimanager@MOODLE_50_STABLE
    strategy:
      matrix:
        php: ['8.3', '8.4']
        moodle: [MOODLE_500_STABLE, MOODLE_501_STABLE, MOODLE_502_STABLE]
        dbtype: [mysqli, sqlsrv]
        include:
          - php: '8.2'
            moodle: MOODLE_500_STABLE
            dbtype: mysqli
          - php: '8.2'
            moodle: MOODLE_500_STABLE
            dbtype: sqlsrv
          - php: '8.2'
            moodle: MOODLE_501_STABLE
            dbtype: mysqli
          - php: '8.2'
            moodle: MOODLE_501_STABLE
            dbtype: sqlsrv

    steps:
      - name: Unit testing & integration testing
        uses: praxisdigital/moodle-test-action@master
        with:
          plugin: assignsubmission_pxaiwriter
          plugin-path: mod/assign/submission/pxaiwriter
          os: ${{ env.OS }}
          php: ${{ matrix.php }}
          dbtype: ${{ matrix.dbtype }}
          moodle: ${{ matrix.moodle }}
          experimental: ${{ env.EXPERIMENTAL }}
          dependencies: ${{ env.DEPENDENCIES }}
          PRIVATE_REPO_TOKEN: ${{ secrets.MOODLE_GH_KEY }}